# 文本校验
text:
  service: "xunfei"
  xunfei:
    appId: ${XUNFEI_APPID:}
    key: ${XUNFEI_KEY:}
    secret: ${XUNFEI_SECRET:}
    url: https://audit.iflyaisol.com//audit/v2/syncText
  aliyun:
    key: ${ALIYUN_KEY:}
    secret: ${ALIYUN_SECRET:}
    region: cn-shanghai
    endpoint: green-cip.cn-shanghai.aliyuncs.com

